// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS2XMISq63c4caEM0NCDnxGfWU-UABpRc',
    appId: '1:53446488005:web:8506c325d671f1dc6365ac',
    messagingSenderId: '53446488005',
    projectId: 'recipesapp-64e47',
    authDomain: 'recipesapp-64e47.firebaseapp.com',
    databaseURL: 'https://recipesapp-64e47-default-rtdb.firebaseio.com',
    storageBucket: 'recipesapp-64e47.appspot.com',
    measurementId: 'G-8Y2M4F53KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEXzgoVU1NbVpWZUVb4bE_ZxThe2wHifk',
    appId: '1:53446488005:android:0957f0066283eef86365ac',
    messagingSenderId: '53446488005',
    projectId: 'recipesapp-64e47',
    databaseURL: 'https://recipesapp-64e47-default-rtdb.firebaseio.com',
    storageBucket: 'recipesapp-64e47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfQfOjQz5MBXAN02rAi0IJ99jRhsQZpQE',
    appId: '1:53446488005:ios:fa101f922b2ec3dd6365ac',
    messagingSenderId: '53446488005',
    projectId: 'recipesapp-64e47',
    databaseURL: 'https://recipesapp-64e47-default-rtdb.firebaseio.com',
    storageBucket: 'recipesapp-64e47.appspot.com',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfQfOjQz5MBXAN02rAi0IJ99jRhsQZpQE',
    appId: '1:53446488005:ios:fa101f922b2ec3dd6365ac',
    messagingSenderId: '53446488005',
    projectId: 'recipesapp-64e47',
    databaseURL: 'https://recipesapp-64e47-default-rtdb.firebaseio.com',
    storageBucket: 'recipesapp-64e47.appspot.com',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS2XMISq63c4caEM0NCDnxGfWU-UABpRc',
    appId: '1:53446488005:web:f971273381283d746365ac',
    messagingSenderId: '53446488005',
    projectId: 'recipesapp-64e47',
    authDomain: 'recipesapp-64e47.firebaseapp.com',
    databaseURL: 'https://recipesapp-64e47-default-rtdb.firebaseio.com',
    storageBucket: 'recipesapp-64e47.appspot.com',
    measurementId: 'G-52ZCETYXMP',
  );

}